#DEP#org.apache.maven:maven-plugin-api	0.35
#DEP#commons-io:commons-io	0.3
#DEP#org.mockito:mockito-core	0.25
#DEP#org.apache.httpcomponents:httpclient	0.2
#DEP#commons-logging:commons-logging	0.2
#DEP#javax.servlet:servlet-api	0.2
#DEP#org.slf4j:jcl-over-slf4j	0.15
#DEP#mysql:mysql-connector-java	0.15
#DEP#org.springframework:spring-core	0.15
#DEP#org.powermock:powermock-api-mockito	0.1
#DEP#commons-lang:commons-lang	0.1
#DEP#org.apache.maven.plugin-testing:maven-plugin-testing-harness	0.1
#DEP#org.codehaus.groovy:groovy-all	0.1
#DEP#commons-cli:commons-cli	0.1
#DEP#com.fasterxml.jackson.core:jackson-databind	0.1
#DEP#org.osgi:org.osgi.core	0.1
#DEP#org.apache.derby:derby	0.1
#DEP#org.hamcrest:hamcrest-library	0.1
#DEP#org.antlr:antlr	0.1
#DEP#com.google.code.gson:gson	0.1
#DEP#log4j:log4j	0.1
#DEP#org.testng:testng	0.1
#DEP#org.powermock:powermock-module-junit4	0.1
#DEP#org.hamcrest:hamcrest-all	0.1
#DEP#ch.qos.logback:logback-core	0.1
#DEP#org.apache.ant:ant	0.1
#DEP#org.springframework:spring-context	0.1
#DEP#org.springframework:spring-web	0.1
#DEP#org.hamcrest:hamcrest-core	0.1
#DEP#org.slf4j:slf4j-simple	0.1
#DEP#commons-codec:commons-codec	0.1
#DEP#org.projectlombok:lombok	0.1
#DEP#org.elasticsearch:elasticsearch	0.1
#DEP#org.apache.maven.scm:maven-scm-provider-bazaar	0.05
#DEP#com.google.appengine:appengine-api-1.0-sdk	0.05
#DEP#org.fusesource.mqtt-client:mqtt-client	0.05
#DEP#org.apache.openjpa:openjpa-all	0.05
#DEP#com.google.gwt:gwt-codeserver	0.05
#DEP#org.springframework.boot:spring-boot-starter-web	0.05
#DEP#javax.ws.rs:jsr311-api	0.05
#DEP#net.sf.ehcache:ehcache-core	0.05
#DEP#com.sun.xml.bind:jaxb-impl	0.05
#DEP#bsf:bsf	0.05
#DEP#org.apache.maven.scm:maven-scm-test	0.05
#DEP#org.apache.axis2:axis2-adb	0.05
#DEP#com.madgag:org.eclipse.jgit	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-synergy	0.05
#DEP#javax.el:javax.el-api	0.05
#DEP#jline:jline	0.05
#DEP#com.google.appengine:appengine-api-labs	0.05
#DEP#com.android.support.test:rules	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-gittest	0.05
#DEP#commons-collections:commons-collections	0.05
#DEP#org.apache.commons:commons-jci-rhino	0.05
#DEP#org.freemarker:freemarker	0.05
#DEP#org.parboiled:parboiled-core	0.05
#DEP#org.apache.maven.reporting:maven-reporting-api	0.05
#DEP#simple-jndi:simple-jndi	0.05
#DEP#ch.qos.logback:ch.qos.logback	0.05
#DEP#com.atlassian.commonmark:commonmark-ext-gfm-tables	0.05
#DEP#org.apache.maven:org.apache.maven	0.05
#DEP#com.atlassian.commonmark:commonmark-ext-gfm-strikethrough	0.05
#DEP#org.apache.openjpa:openjpa-kernel	0.05
#DEP#com.google.appengine:appengine-tools-sdk	0.05
#DEP#com.android.support:appcompat-v7	0.05
#DEP#org.apache.xbean:xbean-asm5-shaded	0.05
#DEP#org.apache.geronimo.specs:geronimo-activation_1.1_spec	0.05
#DEP#com.github.github:site-maven-plugin	0.05
#DEP#org.apache.maven.scm:maven-scm-api	0.05
#DEP#de.java2html:java2html	0.05
#DEP#org.apache.maven:maven-artifact-manager	0.05
#DEP#hsqldb:hsqldb	0.05
#DEP#org.eclipse.jetty:jetty-webapp	0.05
#DEP#org.beanshell:bsh	0.05
#DEP#com.atlassian.commonmark:commonmark-ext-yaml-front-matter	0.05
#DEP#org.json:json	0.05
#DEP#org.osmdroid:osmdroid-android	0.05
#DEP#org.spockframework:spock-core	0.05
#DEP#org.xerial:sqlite-jdbc	0.05
#DEP#org.apache.maven.doxia:doxia-sink-api	0.05
#DEP#org.apache.maven:maven-artifact	0.05
#DEP#javax.xml.bind:jaxb-api	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-cvsexe	0.05
#DEP#com.android.support.test:runner	0.05
#DEP#com.leanengine.server:leanengine-server-lib	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-jazz	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-vss	0.05
#DEP#org.jmock:jmock	0.05
#DEP#xml-apis:xml-apis	0.05
#DEP#org.jboss.resteasy:resteasy-jaxrs	0.05
#DEP#org.apache.bval:org.apache.bval.bundle	0.05
#DEP#com.google.dagger:dagger-compiler	0.05
#DEP#commons-pool:commons-pool	0.05
#DEP#org.apache.maven:maven-core	0.05
#DEP#org.apache.maven.shared:file-management	0.05
#DEP#com.atlassian.commonmark:commonmark	0.05
#DEP#fr.lteconsulting:hexa.rpc	0.05
#DEP#org.apache.openjpa:openjpa-persistence	0.05
#DEP#com.atlassian.commonmark:commonmark-ext-ins	0.05
#DEP#org.apache.maven.shared:maven-dependency-tree	0.05
#DEP#com.mks.api:mksapi-jar	0.05
#DEP#net.lingala.zip4j:zip4j	0.05
#DEP#org.hsqldb:hsqldb	0.05
#DEP#net.java.dev.stax-utils:stax-utils	0.05
#DEP#org.nuxeo.ecm.distribution:nuxeo-distribution-coreserver	0.05
#DEP#org.netbeans.lib:cvsclient	0.05
#DEP#com.beust:jcommander	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-cvs-commons	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-svn-commons	0.05
#DEP#com.google.gwt:gwt-user	0.05
#DEP#com.atlassian.commonmark:commonmark-ext-autolink	0.05
#DEP#org.jboss.weld.se:weld-se	0.05
#DEP#jakarta-regexp:jakarta-regexp	0.05
#DEP#org.springframework.boot:spring-boot-test	0.05
#DEP#com.google.gwt:gwt-servlet	0.05
#DEP#org.apache.maven.shared:maven-verifier	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-svnexe	0.05
#DEP#org.slf4j:log4j-over-slf4j	0.05
#DEP#org.apache.maven.scm:maven-scm-manager-plexus	0.05
#DEP#org.springframework:spring-orm	0.05
#DEP#fr.lteconsulting:hexa.binding	0.05
#DEP#org.apache.maven.scm:maven-scm-providers-standard	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-local	0.05
#DEP#org.springframework.cloud:spring-cloud-commons	0.05
#DEP#de.greenrobot:eventbus	0.05
#DEP#org.apache.openjpa:openjpa-persistence-jdbc	0.05
#DEP#org.springframework.boot:spring-boot-starter	0.05
#DEP#org.sonatype.plexus:plexus-build-api	0.05
#DEP#fr.lteconsulting:hexa.core	0.05
#DEP#org.jboss.resteasy:resteasy-jackson-provider	0.05
#DEP#com.helger:com.helger	0.05
#DEP#com.atlassian.commonmark:commonmark-ext-heading-anchor	0.05
#DEP#org.apache.openjpa.tools.openjpa-maven-plugin.testing:dependingProject-A	0.05
#DEP#joda-time:joda-time	0.05
#DEP#com.google.appengine:appengine-testing	0.05
#DEP#com.google.gwt:gwt-dev	0.05
#DEP#org.nuxeo.ecm.distribution:nuxeo-distribution	0.05
#DEP#org.apache.openjpa:openjpa	0.05
#DEP#org.codehaus.plexus:org.codehaus.plexus	0.05
#DEP#fr.lteconsulting:hexa.binding.gwt	0.05
#DEP#org.apache.openjpa:openjpa-fetch-statistics	0.05
#DEP#com.google.collections:google-collections	0.05
#DEP#org.assertj:assertj-core	0.05
#DEP#com.google.gwt:gwt	0.05
#DEP#com.google.code.findbugs:jsr305	0.05
#DEP#fr.lteconsulting:hexa.all	0.05
#DEP#org.openjdk.jmh:jmh-generator-annprocess	0.05
#DEP#com.google.gwt:com.google.gwt	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-cvstest	0.05
#DEP#com.android.support:recyclerview-v7	0.05
#DEP#org.apache.maven.shared:maven-plugin-testing-harness	0.05
#DEP#cglib:cglib-nodep	0.05
#DEP#org.springframework:spring-jdbc	0.05
#DEP#com.h2database:h2	0.05
#DEP#org.slf4j:slf4j-ext	0.05
#DEP#org.easymock:easymockclassextension	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-perforce	0.05
#DEP#org.springframework.boot:spring-boot-actuator	0.05
#DEP#org.apache.axis2:axis2-transport-http	0.05
#DEP#com.android.support:cardview-v7	0.05
#DEP#org.apache.geronimo.specs:geronimo-jpa_2.1_spec	0.05
#DEP#org.nibor.autolink:autolink	0.05
#DEP#org.slf4j:jul-to-slf4j	0.05
#DEP#com.atlassian.commonmark:commonmark-test-util	0.05
#DEP#commons-dbcp:commons-dbcp	0.05
#DEP#org.nuxeo.build:ant-assembly-maven-plugin	0.05
#DEP#org.springframework.cloud:spring-cloud-starter-consul-discovery	0.05
#DEP#org.nuxeo.ecm.platform:nuxeo-platform-test	0.05
#DEP#org.apache.commons:commons-compress	0.05
#DEP#org.apache.ant:ant-antunit	0.05
#DEP#com.github.japgolly.android:svg-android	0.05
#DEP#org.apache.maven:maven-model	0.05
#DEP#javax.enterprise:cdi-api	0.05
#DEP#com.google.dagger:dagger	0.05
#DEP#org.apache.geronimo.specs:geronimo-validation_1.1_spec	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-svntest	0.05
#DEP#com.helger:ph-css	0.05
#DEP#org.springframework.cloud:spring-cloud-dependencies	0.05
#DEP#org.apache.ws.commons.axiom:axiom-impl	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-git-commons	0.05
#DEP#org.postgresql:postgresql	0.05
#DEP#org.jmock:jmock-junit4	0.05
#DEP#org.apache.maven:maven-repository-metadata	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-tfs	0.05
#DEP#org.openjdk.jmh:jmh-core	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-clearcase	0.05
#DEP#org.parboiled:parboiled-java	0.05
#DEP#com.spatial4j:spatial4j	0.05
#DEP#org.apache.axis2:axis2-kernel	0.05
#DEP#org.firebirdsql.jdbc:jaybird-jdk17	0.05
#DEP#org.eclipse.jetty:jetty-server	0.05
#DEP#com.squareup:com.squareup	0.05
#DEP#fr.lteconsulting:hexa.css	0.05
#DEP#org.apache.openjpa:openjpa-jdbc	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-hg	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-accurev	0.05
#DEP#postgresql:postgresql	0.05
#DEP#net.sourceforge.serp:serp	0.05
#DEP#de.sciss:netutil	0.05
#DEP#com.ecwid.consul:consul-api	0.05
#DEP#com.github.stefanbirkner:system-rules	0.05
#DEP#commons-beanutils:commons-beanutils	0.05
#DEP#org.apache.httpcomponents:httpcore	0.05
#DEP#ch.ethz.ganymed:ganymed-ssh2	0.05
#DEP#org.apache.wink:wink-common	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-starteam	0.05
#DEP#com.github.darren-fu:resty-pass	0.05
#DEP#com.google.appengine:appengine-api-stubs	0.05
#DEP#com.ibm.websphere:websphere_uow_api	0.05
#DEP#com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru	0.05
#DEP#org.liquibase:liquibase-core	0.05
#DEP#org.apache.velocity:velocity	0.05
#DEP#org.mockito:mockito-all	0.05
#DEP#org.apache.axis2:axis2-transport-local	0.05
#DEP#com.microsoft.sqlserver:mssql-jdbc	0.05
#DEP#org.apache.geronimo.specs:geronimo-jms_1.1_spec	0.05
#DEP#org.jsoup:jsoup	0.05
#DEP#org.asynchttpclient:async-http-client	0.05
#DEP#org.apache.geronimo.specs:geronimo-jta_1.1_spec	0.05
#DEP#com.android.support:palette-v7	0.05
#DEP#org.objenesis:objenesis	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-gitexe	0.05
#DEP#org.apache.maven:maven-settings	0.05
#DEP#org.sonatype.plexus:plexus-sec-dispatcher	0.05
#DEP#javax.servlet.jsp:jsp-api	0.05
#DEP#org.nuxeo.connect:nuxeo-connect-client	0.05
#DEP#org.apache.maven.plugin-tools:org.apache.maven.plugin-tools	0.05
#DEP#fr.lteconsulting:hexa.utils	0.05
#DEP#org.fusesource.jansi:jansi	0.05
#DEP#org.hibernate.javax.persistence:hibernate-jpa-2.0-api	0.05
#DEP#org.codehaus.plexus:plexus-container-default	0.05
#DEP#org.apache.maven.scm:maven-scm-provider-cvsjava	0.05
#DEP#httpunit:httpunit	0.05
#DEP#org.springframework:spring-beans	0.05
#DEP#org.apache.openjpa:openjpa-lib	0.05
#DEP#org.owasp:dependency-check-maven	0.05
#DEP#org.mariadb.jdbc:mariadb-java-client	0.05
#DEP#org.eclipse.jetty:jetty-servlet	0.05
#DEP#org.jrack:jrack	0.05
