#DEP#log4j:log4j	1
#DEP#org.slf4j:slf4j-log4j12	1
#DEP#org.mockito:mockito-core	1
#DEP#junit:junit	1
#DEP#commons-io:commons-io	1
#DEP#org.pegdown:pegdown	1
#DEP#com.google.guava:guava	1
#DEP#org.sonatype.oss:oss-parent	1
#DEP#org.apache.httpcomponents:httpclient	1
#DEP#org.apache.maven:maven-plugin-api	1
#DEP#org.codehaus.plexus:plexus-utils	1
#DEP#org.slf4j:slf4j-api	1
#DEP#org.yaml:snakeyaml	1
#DEP#org.json:json	1
#DEP#javax.servlet:servlet-api	1
#DEP#org.mozilla:rhino	1
#DEP#commons-logging:commons-logging	1
#DEP#org.apache.maven.plugin-tools:maven-plugin-annotations	1
#DEP#org.apache.maven:maven-project	1
#DEP#ch.qos.logback:logback-classic	1
#DEP#org.apache.commons:commons-lang3	1
#DEP#org.parboiled:parboiled-core	1
#DEP#org.springframework:spring-context	1
#DEP#org.springframework:spring-beans	1
#DEP#org.parboiled:parboiled-java	1
#DEP#mysql:mysql-connector-java	1
#DEP#commons-lang:commons-lang	1
#DEP#org.springframework:spring-core	1
#DEP#org.apache.httpcomponents:httpmime	1
#DEP#javax.servlet:javax.servlet-api	1
#DEP#com.atlassian.commonmark:commonmark	1
#DEP#com.sun.mail:javax.mail	1
#DEP#org.aspectj:aspectjweaver	1
#DEP#commons-fileupload:commons-fileupload	1
#DEP#commons-cli:commons-cli	1
