1	git://github.com/spullara/mustache.java.git
2	#DEP#com.github.spullara.mustache.java:scala-extensions
3	#DEP#org.apache.maven.plugin-tools:maven-plugin-annotations
4	#DEP#com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
5	#DEP#org.codehaus.plexus:plexus-compiler-api
6	#DEP#com.github.spullara.cli-parser:cli-parser
7	#DEP#com.fasterxml.jackson.core:jackson-databind
8	#DEP#com.github.spullara.mustache.java:compiler
9	#DEP#com.twitter:util-core_2.12
10	#DEP#com.github.spullara.mustache.java:mustache.java
11	#DEP#org.apache.maven:maven-plugin-api
12	#DEP#com.twitter:util-core_2.10
13	#DEP#com.twitter:util-core_2.11
14	#DEP#com.fasterxml.jackson.core:jackson-core
15	#DEP#org.openjdk.jmh:jmh-generator-annprocess
16	#DEP#org.scala-lang:scala-library
17	#DEP#org.eclipse.jetty:jetty-server
18	#DEP#com.google.guava:guava
19	#DEP#junit:junit
20	#DEP#org.openjdk.jmh:jmh-core
