1	git://github.com/hyb1996/Auto.js.git
2	#DEP#com.squareup.leakcanary:leakcanary-android
3	#DEP#io.reactivex.rxjava2:rxandroid
4	#DEP#com.squareup.okhttp3:okhttp
5	#DEP#com.squareup.leakcanary:leakcanary-android-no-op
6	#DEP#com.github.hyb1996:FloatingCircularActionMenu
7	#DEP#com.github.hyb1996:android-multi-level-listview
8	#DEP#com.google.code.findbugs:jsr305
9	#DEP#org.greenrobot:eventbus
10	#DEP#com.github.hyb1996:MutableTheme
11	#DEP#com.wang.avi:library
12	#DEP#com.squareup.retrofit2:converter-gson
13	#DEP#com.flurry.android:analytics
14	#DEP#com.github.hyb1996:settingscompat
15	#DEP#com.yqritc:recyclerview-flexibledivider
16	#DEP#com.squareup.retrofit2:retrofit
17	#DEP#com.github.Raizlabs.DBFlow:dbflow-processor
18	#DEP#com.makeramen:roundedimageview
19	#DEP#com.android.support:support-annotations
20	#DEP#com.bignerdranch.android:expandablerecyclerview
21	#DEP#io.reactivex.rxjava2:rxjava
22	#DEP#com.github.Raizlabs.DBFlow:dbflow-core
23	#DEP#com.github.Raizlabs.DBFlow:dbflow-rx2
24	#DEP#com.twofortyfouram:android-plugin-client-sdk-for-locale
25	#DEP#com.github.hyb1996:OpenCvLib
26	#DEP#com.jakewharton:butterknife-compiler
27	#DEP#com.github.atlassian:commonmark-java
28	#DEP#org.apache.commons:commons-lang3
29	#DEP#com.android.support:appcompat-v7
30	#DEP#com.github.Raizlabs.DBFlow:dbflow
31	#DEP#com.github.hyb1996:EnhancedFloaty
32	#DEP#com.google.code.gson:gson
33	#DEP#com.android.support:design
34	#DEP#joda-time:joda-time
35	#DEP#org.jdeferred:jdeferred-android-aar
36	#DEP#com.github.Stericson:RootShell
37	#DEP#de.psdev.licensesdialog:licensesdialog
38	#DEP#com.android.support:cardview-v7
39	#DEP#net.lingala.zip4j:zip4j
40	#DEP#com.github.bumptech.glide:compiler
41	#DEP#com.android.support:multidex
42	#DEP#com.github.hyb1996:Auto.js-ApkBuilder
43	#DEP#com.jakewharton.retrofit:retrofit2-rxjava2-adapter
44	#DEP#junit:junit
45	#DEP#com.thoughtbot:expandablerecyclerview
