#DEP#junit:junit	1
#DEP#org.codehaus.plexus:plexus-utils	1
#DEP#org.codehaus.plexus:plexus-compiler-api	1
#DEP#org.apache.maven:maven-plugin-api	1
#DEP#commons-lang:commons-lang	1
#DEP#commons-io:commons-io	1
#DEP#com.github.spullara.mustache.java:compiler	1
#DEP#org.slf4j:slf4j-api	1
#DEP#com.fasterxml.jackson.core:jackson-databind	1
#DEP#org.apache.maven:maven-project	1
#DEP#com.google.guava:guava	1
#DEP#org.slf4j:slf4j-simple	1
#DEP#org.apache.maven:maven-artifact	1
#DEP#org.apache.maven:maven-core	1
#DEP#org.codehaus.plexus:plexus-container-default	1
#DEP#commons-collections:commons-collections	1
#DEP#org.mockito:mockito-core	1
#DEP#org.freemarker:freemarker	1
#DEP#org.apache.maven.plugin-tools:maven-plugin-annotations	1
#DEP#org.apache.maven:maven-model	1
#DEP#org.eclipse.jetty:jetty-server	1
#DEP#javax.servlet:javax.servlet-api	1
#DEP#org.apache.maven:maven-archiver	1
#DEP#com.fasterxml.jackson.core:jackson-core	1
#DEP#org.apache.commons:commons-lang3	1
#DEP#commons-cli:commons-cli	1
#DEP#com.github.spullara.cli-parser:cli-parser	1
#DEP#org.apache.maven.plugin-testing:maven-plugin-testing-harness	1
#DEP#com.fasterxml.jackson.core:jackson-annotations	1
#DEP#org.apache.maven:maven-compat	1
#DEP#org.seleniumhq.selenium:selenium-java	1
#DEP#org.apache.maven.shared:file-management	1
#DEP#commons-logging:commons-logging	1
#DEP#org.antlr:antlr4-runtime	1
#DEP#io.netty:netty-all	1
