1	git://github.com/shizuchengxuyuan/net.sz.java.git
2	#DEP#mysql:mysql-connector-java
3	#DEP#io.netty:netty-all
4	#DEP#com.vividsolutions:jts
5	#DEP#com.thoughtworks.xstream:xstream
6	#DEP#redis.clients:jedis
7	#DEP#${project.groupId}:net.sz.framework.szthread
8	#DEP#org.xerial:sqlite-jdbc
9	#DEP#com.google.protobuf:protobuf-java
10	#DEP#javax.mail:mail
11	#DEP#com.mashape.unirest:unirest-java
12	#DEP#${project.groupId}:net.sz.framework.szlog
13	#DEP#${project.groupId}:net.sz.framework.utils
14	#DEP#org.mongodb:mongo-java-driver
15	#DEP#org.apache.httpcomponents:httpclient
16	#DEP#${project.groupId}:net.sz.framework.nio
17	#DEP#${project.groupId}:net.sz.framework.db
18	#DEP#com.alibaba:fastjson
19	#DEP#net.sz.framework:net.sz.framework
20	#DEP#com.squareup.retrofit:converter-simplexml
21	#DEP#com.google.code.gson:gson
22	#DEP#c3p0:c3p0
23	#DEP#${project.groupId}:net.sz.framework.way.navmesh
24	#DEP#junit:junit
25	#DEP#${project.groupId}:net.sz.framework.script
