1	#DEP#com.twofortyfouram:android-plugin-client-sdk-for-locale
1	#DEP#com.github.hyb1996:OpenCvLib
1	#DEP#com.jakewharton:butterknife-compiler
1	#DEP#com.github.atlassian:commonmark-java
1	#DEP#org.apache.commons:commons-lang3
1	#DEP#com.android.support:appcompat-v7
1	#DEP#com.github.Raizlabs.DBFlow:dbflow
1	#DEP#com.github.hyb1996:EnhancedFloaty
1	#DEP#com.google.code.gson:gson
1	#DEP#com.android.support:design
1	#DEP#joda-time:joda-time
1	#DEP#org.jdeferred:jdeferred-android-aar
1	#DEP#com.github.Stericson:RootShell
1	#DEP#de.psdev.licensesdialog:licensesdialog
1	#DEP#com.android.support:cardview-v7
1	#DEP#net.lingala.zip4j:zip4j
1	#DEP#com.github.bumptech.glide:compiler
1	#DEP#com.android.support:multidex
1	#DEP#com.github.hyb1996:Auto.js-ApkBuilder
1	#DEP#com.jakewharton.retrofit:retrofit2-rxjava2-adapter
1	#DEP#junit:junit
1	#DEP#com.thoughtbot:expandablerecyclerview
